// <auto-generated />
namespace VirtoCommerce.Mobile.SyncModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddMainColor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMainColor));
        
        string IMigrationMetadata.Id
        {
            get { return "201611211437415_AddMainColor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
